### ISSUE TITLE
Tags lacking for the Expressive (Fae-Touched) merit.

### ISSUE THREAD

**Issue by Rucket82** [thenomain/GMCCG#44]
https://github.com/thenomain/GMCCG/blob/6e128d9434f778825ec19feb4a213cf12f354fbe/Z%20-%20Game%20Lines/Changeling%20the%20Lost/CtL1%20-%20Core.txt#L550-L551

It's lacking the tags for the merit, should probably be:

&tags.merit.expressive [v(d.dt)]=fae-touched

**Comment by thenomain** [comment]
Unfortunately when tags overlap templates, it limits the trait to that template. This is an unfortunate side-effect of how I set up tags. If I did it again, there would be 'templates.<statpath>' for template limiters and 'tags.<statpath>' for other informative and code-based tags.

Because we add "Fae-Touched" to the valid template list in line 85-87, if you added "&tags.merit.expressive [v(d.dt)]=fae-touched", then only fae-touched could take this merit.

If you're running a Changeling-only game, this probably wouldn't be a problem. If you have Humans in the template list, tho, then they as non-Changelings couldn't take this merit. I can see the book being read either way; this is just the most literal way I took it at the time.
